---
vpc_cidr: 10.46.0.0/16
aws_region: us-west-2
vpc_prefix: "acit4640"
aws_az: us-west-2a
vpc_subnet_cidr: 10.46.10.0/24
keypair: aws_private_key
instance_type: t2.micro
image: ami-01ed306a12b7d1c96
ec2_instance_name: flaskr_app
