---
- name: Install nginx
  become: yes
  package:
    name:
      - nginx

- name: Move nginx config
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: nginx

- name: Start and enable nginx
  become: yes
  systemd:
    name: nginx
    enabled: yes
