---
- name: Install mongodb
  become: yes
  package:
    name:
      - mongodb
      - mongodb-server

- name: Set up database.js
  become: yes
  template:
    src: database.js
    dest: /home/todoapp/app/config/database.js

- name: Copy pre-existing data
  become: yes
  copy:
    src: ACIT4640
    dest: /home/admin

- name: export lang
  become: yes
  shell: export LANG=C

- name: Start mongod service
  become: yes
  systemd:
    name: mongod
    state: started
    enabled: yes
  notify: import data 
