---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws

- hosts: aws_ec2
  gather_facts: False
  vars:
    admin_user_name: admin
    flaskr_user: centos
    flaskr_path: /home/centos/flaskr
    flaskr_port: 5000
  roles:
    - flask
  tags:
    - deploy
