---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws

- hosts: aws_ec2
  gather_facts: False
  vars:
    admin_user_name: admin
    flaskr_port: 5000
  roles:
    - flask
  tags:
    - deployment
