---
- name: Clone flask app
  become: yes
  git:
    clone: yes
    repo: "https://github.com/naohashizume/flaskr.git"
    dest: /home/centos/flaskr
    force: yes

- name: Change ownership of flask app
  become: yes
  file:
    path: /home/centos/flaskr
    state: directory
    recurse: yes
    owner: centos
    group: centos

    #- name: Create virtual environment
    #become: yes
    #command: python3 -m venv venv
  #  become: yes
  #args:
  #chdir: /home/centos/flaskr

    #- name: Activate venv
    #become: yes
    #command: . venv/bin/activate
    #args:
    #chdir: /home/centos/flaskr

- name: Install requirements
  command: pip3 install -r requirements.txt
  become: yes
  args:
    chdir: /home/centos/flaskr

- name: Export LC_ALL
  become: yes
  lineinfile:
    path: /etc/environment
    line: export LC_ALL=en_US.UTF-8

- name: Export FLASK_APP
  become: yes
  lineinfile:
    path: /etc/environment
    line: export FLASK_APP=flaskr
    create: yes

- name: Export FLASK_ENV
  become: yes
  lineinfile:
    path: /etc/environment
    line: export FLASK_ENV=development
    create: yes

- name: Source environemnt
  become: yes
  shell: source /etc/environment

- name: Init db
  shell: flask init-db
  args:
    chdir: /home/centos/flaskr

- name: Reload system
  become: yes
  systemd:
    daemon_reload: yes

- name: Start services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - flaskr

