---
- name: Clone flask app
  become: yes
  git:
    clone: yes
    repo: "https://github.com/naohashizume/flaskr.git"
    dest: "{{ flaskr_path }}"
    force: yes

- name: Change ownership of flask app
  become: yes
  file:
    path: "{{ flaskr_path }}"
    state: directory
    recurse: yes
    owner: "{{ flaskr_user }}"
    group: "{{ flaskr_user }}"

- name: Install requirements
  command: pip3 install -r requirements.txt
  become: yes
  args:
    chdir: "{{ flaskr_path }}"

- name: Source environemnt
  become: yes
  shell: source /etc/environment

- name: Reload system
  become: yes
  systemd:
    daemon_reload: yes

- name: Start services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - flaskr
