---
- name: Clone flask tutorial
  become: yes
  git:
    clone: yes
    repo: "https://github.com/naohashizume/flaskr.git"
    dest: /home/centos/flaskr
    force: yes

    #- pip:
    #chdir: /home/centos/flaskr
    #requirements: requirements.txt
    #virtualenv_python: venv

- name: Create virtual environment
  command: python3 -m venv venv
  become: yes
  args:
    chdir: /home/centos/flaskr

    #- name: Activate venv
    #command: . venv/bin/activate
    #args:
    #chdir: /home/centos/flaskr

- name: Install requirements
  command: pip install -r requirements.txt
  become: yes
  args:
    chdir: /home/centos/flaskr

- name: Export LC_ALL
  shell: export LC_ALL=en_US.UTF-8

- name: Export FLASK_APP
  become: yes
  lineinfile:
    path: /etc/environment
    line: export FLASK_APP=flaskr
    create: yes

- name: Export FLASK_ENV
  become: yes
  lineinfile:
    path: /etc/environment
    line: export FLASK_ENV=development
    create: yes

- name:
  become: yes
  shell: source /etc/environment

- name: Init db
  command: "flask init-db"
  args:
    chdir: /home/centos/flaskr

- name: Start services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - flaskr

- name: Reload system
  become: yes
  systemd:
    daemon_reload: yes

