---
- name: Clone flask app
  become: yes
  git:
    clone: yes
    repo: "https://github.com/naohashizume/flaskr.git"
    dest: /home/centos/flaskr
    force: yes

- name: Create virtual environment
  command: python3 -m venv venv
  become: yes
  args:
    chdir: /home/centos/flaskr

- name: Install requirements
  command: pip install -r requirements.txt
  become: yes
  args:
    chdir: /home/centos/flaskr

- name: Init db
  command: "flask init-db"
  args:
    chdir: /home/centos/flaskr

- name: Reload system
  become: yes
  systemd:
    daemon_reload: yes

- name: Start services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - flaskr
