- ec2_instance_facts:
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
  register: instance_facts

- name: Print ec2 public IP
  debug:
    msg: "{{ instance_facts.instances[0].public_ip_address }}"

