---
- name: Set up todoapp.service
  become: yes
  template:
    src: flaskr.service
    dest: /etc/systemd/system

- name: Export
  shell: "export FLASK_APP=flaskr"

- name: Export
  shell: "export FLASK_ENV=development"

- name: Export
  shell: "export LC_ALL=en_US.UTF-8"

- name: Set up flaskr.service
  become: yes
  template:
    src: flaskr.service
    dest: /etc/systemd/system
